---
- name: Create private key for CA
  community.crypto.openssl_privatekey:
    path: /etc/pki/CA/private/ca-certificate.key
    passphrase: "{{ secret_ca_passphrase }}"
    cipher: auto
    size: 2048
    type: RSA
  become: yes

- name: Create CA certificate signing request (CSR)
  community.crypto.openssl_csr_pipe:
    privatekey_path: /etc/pki/CA/private/ca-certificate.key
    privatekey_passphrase: "{{ secret_ca_passphrase }}"

    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    organization_name: "{{ organization_name }}"
    organizational_unit_name: "{{ organizational_unit_name }}"
    common_name: "{{ common_name }}"
    use_common_name_for_san: false

    basic_constraints: "CA:TRUE"
    basic_constraints_critical: yes
  register: ca_csr
  become: yes

- name: Print CSR
  ansible.builtin.debug:
    msg: "{{ ca_csr }}"

- name: Create CA certificate from CSR
  community.crypto.x509_certificate:
    path: /etc/pki/CA/certs/ca-certificate.crt
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: /etc/pki/CA/private/ca-certificate.key
    privatekey_passphrase: "{{ secret_ca_passphrase }}"

    selfsigned_not_after: +3650d
    selfsigned_digest: sha256
    provider: selfsigned

    state: present
    return_content: yes
  register: ca_crt
  become: yes

- name: Get CA certificate in control node 
  ansible.builtin.copy:
    content: "{{ ca_crt.certificate }}"
    dest: /tmp/ca.crt
  delegate_to: 127.0.0.1
  tags:
    - never
