---
- name: Create private key for new certificate
  community.crypto.openssl_privatekey:
    path: "{{ dir_key }}/{{ common_name }}.key"
    passphrase: "{{ secret_passphrase }}"
    cipher: auto
    size: 2048
    type: RSA
  become: yes

- name: Create server certificate signing request (CSR)
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ dir_key }}/{{ common_name }}.key"
    privatekey_passphrase: "{{ secret_passphrase }}"

    country_name: "{{ country_name }}"
    state_or_province_name: "{{ state_or_province_name }}"
    locality_name: "{{ locality_name }}"
    organization_name: "{{ organization_name }}"
    organizational_unit_name: "{{ organizational_unit_name }}"

    subject_alt_name:
      - "DNS:{{ common_name.split('.')[1:] | join('.') }}"
      - "DNS:{{ common_name }}"
  register: server_csr
  become: yes

- name: Store CSR file created
  ansible.builtin.copy:
    content: "{{ server_csr.csr }}"
    dest: "{{ dir_csr }}/{{ common_name }}.csr"
  become: yes

- name: Get CSR file in control node
  ansible.builtin.copy:
    content: "{{ server_csr.csr }}"
    dest: /tmp/{{ common_name }}.csr
  delegate_to: 127.0.0.1
  tags:
    - never
