---
- hosts: all

# This playbook run all setup needed to use community.crypto 2.3.2 if using default variables
  roles:
    - role: openssl-install
    - role: python3-install
    - role: ansible-install
      tags: [ local ]
    - role: cryptography-install

  post_tasks:
    - name: Refresh table of recently executed programs
      ansible.builtin.shell:
        cmd: hash -r
      tags:
        - local

    - name: Remove old Ansible yum installation
      ansible.builtin.yum:
        name: ansible
        state: absent
      become: yes
      tags:
        - local

